// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prokat.API.Data;

#nullable disable

namespace Prokat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407090504_AddClientProfileFields")]
    partial class AddClientProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prokat.API.DTO.InventoryDto", b =>
                {
                    b.Property<int>("ID_Инвентаря")
                        .HasColumnType("int");

                    b.Property<string>("Ботинки")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Лыжи")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Палки")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Сноуборд")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("InventoryDto", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Prokat.API.DTO.OrderResultDto", b =>
                {
                    b.Property<int>("ID_Заказа")
                        .HasColumnType("int");

                    b.Property<decimal>("ИтоговаяСумма")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.ToTable("OrderResultDto", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Prokat.API.Models.AppUser", b =>
                {
                    b.Property<int>("ID_Учетной_записи")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Учетной_записи"));

                    b.Property<int?>("ID_Клиента")
                        .HasColumnType("int");

                    b.Property<string>("Логин")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ПарольХеш")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Роль")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("ID_Учетной_записи");

                    b.HasIndex("ID_Клиента");

                    b.HasIndex("Логин")
                        .IsUnique();

                    b.ToTable("Учетная_запись", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.Client", b =>
                {
                    b.Property<int>("ID_Клиента")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Клиента"));

                    b.Property<int?>("ID_Заказа")
                        .HasColumnType("int");

                    b.Property<int?>("Вес")
                        .HasColumnType("int");

                    b.Property<int?>("Возраст")
                        .HasColumnType("int");

                    b.Property<int?>("Залог")
                        .HasColumnType("int");

                    b.Property<string>("Имя")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("РазмерОбуви")
                        .HasColumnType("int");

                    b.Property<int?>("Рост")
                        .HasColumnType("int");

                    b.Property<string>("Фамилия")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ФотоПрофиля")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Клиента");

                    b.ToTable("Клиент", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.Inventory", b =>
                {
                    b.Property<int>("ID_Инвентаря")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Инвентаря"));

                    b.Property<int?>("ID_Техника_консультанта")
                        .HasColumnType("int");

                    b.Property<string>("Ботинки")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Лыжи")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Маска")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Одежда")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Палки")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Скипасс")
                        .HasColumnType("int");

                    b.Property<string>("Сноуборд")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Шлем")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Инвентаря");

                    b.ToTable("Инвентарь", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.Order", b =>
                {
                    b.Property<int>("ID_Заказа")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Заказа"));

                    b.Property<int?>("ID_Администратора")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Клиента")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Техника_консультанта")
                        .HasColumnType("int");

                    b.Property<decimal?>("БазоваяСумма")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Сумма_оплаты")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("ID_Заказа");

                    b.ToTable("Счет_оплаты", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.PriceTariff", b =>
                {
                    b.Property<int>("Время_аренды")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Администратора")
                        .HasColumnType("int");

                    b.Property<int?>("Абонемент")
                        .HasColumnType("int");

                    b.Property<int?>("Прокат_будни")
                        .HasColumnType("int");

                    b.Property<int?>("Прокат_выходные_и_праздничные_дни")
                        .HasColumnType("int");

                    b.Property<int?>("Скипасс_будни")
                        .HasColumnType("int");

                    b.Property<int?>("Скипасс_выходные_и_праздиничные_дни")
                        .HasColumnType("int");

                    b.Property<int?>("Штраф")
                        .HasColumnType("int");

                    b.HasKey("Время_аренды");

                    b.ToTable("Цены_на_услуги", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.RentalBooking", b =>
                {
                    b.Property<int>("ID_Аренды")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Аренды"));

                    b.Property<int>("ID_Заказа")
                        .HasColumnType("int");

                    b.Property<int>("ID_Инвентаря")
                        .HasColumnType("int");

                    b.Property<DateTime>("ДатаНачала")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ДатаОкончания")
                        .HasColumnType("datetime2");

                    b.Property<string>("Статус")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Аренды");

                    b.HasIndex("ID_Заказа");

                    b.HasIndex("ID_Инвентаря");

                    b.ToTable("Аренда_бронирование", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.SiteSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("СтавкаНДС")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("ID");

                    b.ToTable("Настройки_проката", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.AppUser", b =>
                {
                    b.HasOne("Prokat.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ID_Клиента")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Prokat.API.Models.RentalBooking", b =>
                {
                    b.HasOne("Prokat.API.Models.Order", "Order")
                        .WithMany("Rentals")
                        .HasForeignKey("ID_Заказа")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prokat.API.Models.Inventory", "Inventory")
                        .WithMany("Rentals")
                        .HasForeignKey("ID_Инвентаря")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Prokat.API.Models.Inventory", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Prokat.API.Models.Order", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
