// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prokat.API.Data;

#nullable disable

namespace Prokat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260419142206_SplitInventoryDomainTables")]
    partial class SplitInventoryDomainTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prokat.API.DTO.InventoryDto", b =>
                {
                    b.Property<int>("ID_Инвентаря")
                        .HasColumnType("int");

                    b.Property<string>("Ботинки")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Лыжи")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Палки")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Сноуборд")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("InventoryDto", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Prokat.API.DTO.OrderResultDto", b =>
                {
                    b.Property<int>("ID_Заказа")
                        .HasColumnType("int");

                    b.Property<decimal>("ИтоговаяСумма")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.ToTable("OrderResultDto", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Prokat.API.Models.AppUser", b =>
                {
                    b.Property<int>("ID_Учетной_записи")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Учетной_записи"));

                    b.Property<int?>("ID_Клиента")
                        .HasColumnType("int");

                    b.Property<string>("Логин")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ПарольХеш")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Роль")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("ID_Учетной_записи");

                    b.HasIndex("ID_Клиента");

                    b.HasIndex("Логин")
                        .IsUnique();

                    b.ToTable("Учетная_запись", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.BootsItem", b =>
                {
                    b.Property<int>("ID_Ботинки")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Ботинки"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Примечание")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("РазмерEU")
                        .HasColumnType("int");

                    b.Property<string>("Тип")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Ботинки");

                    b.ToTable("Ботинки", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.Client", b =>
                {
                    b.Property<int>("ID_Клиента")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Клиента"));

                    b.Property<int?>("ID_Заказа")
                        .HasColumnType("int");

                    b.Property<int?>("Вес")
                        .HasColumnType("int");

                    b.Property<int?>("Возраст")
                        .HasColumnType("int");

                    b.Property<int?>("Залог")
                        .HasColumnType("int");

                    b.Property<string>("Имя")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("РазмерОбуви")
                        .HasColumnType("int");

                    b.Property<int?>("Рост")
                        .HasColumnType("int");

                    b.Property<string>("Фамилия")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ФотоПрофиля")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Клиента");

                    b.ToTable("Клиент", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.GogglesItem", b =>
                {
                    b.Property<int>("ID_Очки")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Очки"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Размер")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ТипЛинзы")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Очки");

                    b.ToTable("Очки", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.HelmetItem", b =>
                {
                    b.Property<int>("ID_Шлем")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Шлем"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Размер")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Тип")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Шлем");

                    b.ToTable("Шлемы", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.Inventory", b =>
                {
                    b.Property<int>("ID_Инвентаря")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Инвентаря"));

                    b.Property<int?>("ID_Ботинки")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Лыжи")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Очки")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Палки")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Сноуборд")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Техника_консультанта")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Шлем")
                        .HasColumnType("int");

                    b.Property<int?>("Скипасс")
                        .HasColumnType("int");

                    b.HasKey("ID_Инвентаря");

                    b.HasIndex("ID_Ботинки");

                    b.HasIndex("ID_Лыжи");

                    b.HasIndex("ID_Очки");

                    b.HasIndex("ID_Палки");

                    b.HasIndex("ID_Сноуборд");

                    b.HasIndex("ID_Шлем");

                    b.ToTable("Инвентарь", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.Order", b =>
                {
                    b.Property<int>("ID_Заказа")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Заказа"));

                    b.Property<int?>("ID_Администратора")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Клиента")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Техника_консультанта")
                        .HasColumnType("int");

                    b.Property<decimal?>("БазоваяСумма")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Сумма_оплаты")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("ID_Заказа");

                    b.ToTable("Счет_оплаты", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.PolesItem", b =>
                {
                    b.Property<int>("ID_Палки")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Палки"));

                    b.Property<int>("ДлинаСм")
                        .HasColumnType("int");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Примечание")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Тип")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Палки");

                    b.ToTable("Палки", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.PriceTariff", b =>
                {
                    b.Property<int>("Время_аренды")
                        .HasColumnType("int");

                    b.Property<int?>("ID_Администратора")
                        .HasColumnType("int");

                    b.Property<int?>("Абонемент")
                        .HasColumnType("int");

                    b.Property<int?>("Прокат_будни")
                        .HasColumnType("int");

                    b.Property<int?>("Прокат_выходные_и_праздничные_дни")
                        .HasColumnType("int");

                    b.Property<int?>("Скипасс_будни")
                        .HasColumnType("int");

                    b.Property<int?>("Скипасс_выходные_и_праздиничные_дни")
                        .HasColumnType("int");

                    b.Property<int?>("Штраф")
                        .HasColumnType("int");

                    b.HasKey("Время_аренды");

                    b.ToTable("Цены_на_услуги", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.RentalBooking", b =>
                {
                    b.Property<int>("ID_Аренды")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Аренды"));

                    b.Property<int>("ID_Заказа")
                        .HasColumnType("int");

                    b.Property<int>("ID_Инвентаря")
                        .HasColumnType("int");

                    b.Property<DateTime>("ДатаНачала")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ДатаОкончания")
                        .HasColumnType("datetime2");

                    b.Property<string>("Статус")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Аренды");

                    b.HasIndex("ID_Заказа");

                    b.HasIndex("ID_Инвентаря");

                    b.ToTable("Аренда_бронирование", null, t =>
                        {
                            t.HasTrigger("TRG_Аренда_Проверки");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Prokat.API.Models.SiteSettings", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("СтавкаНДС")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("ID");

                    b.ToTable("Настройки_проката", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.SkiItem", b =>
                {
                    b.Property<int>("ID_Лыжи")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Лыжи"));

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Примечание")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("РостовкаСм")
                        .HasColumnType("int");

                    b.Property<string>("Тип")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Уровень")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Лыжи");

                    b.ToTable("Лыжи", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.SnowboardItem", b =>
                {
                    b.Property<int>("ID_Сноуборд")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Сноуборд"));

                    b.Property<string>("Жесткость")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Примечание")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("РостовкаСм")
                        .HasColumnType("int");

                    b.Property<string>("Тип")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Сноуборд");

                    b.ToTable("Сноуборды", (string)null);
                });

            modelBuilder.Entity("Prokat.API.Models.AppUser", b =>
                {
                    b.HasOne("Prokat.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ID_Клиента")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Prokat.API.Models.Inventory", b =>
                {
                    b.HasOne("Prokat.API.Models.BootsItem", "Ботинки")
                        .WithMany()
                        .HasForeignKey("ID_Ботинки")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Prokat.API.Models.SkiItem", "Лыжи")
                        .WithMany()
                        .HasForeignKey("ID_Лыжи")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Prokat.API.Models.GogglesItem", "Очки")
                        .WithMany()
                        .HasForeignKey("ID_Очки")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Prokat.API.Models.PolesItem", "Палки")
                        .WithMany()
                        .HasForeignKey("ID_Палки")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Prokat.API.Models.SnowboardItem", "Сноуборд")
                        .WithMany()
                        .HasForeignKey("ID_Сноуборд")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Prokat.API.Models.HelmetItem", "Шлем")
                        .WithMany()
                        .HasForeignKey("ID_Шлем")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ботинки");

                    b.Navigation("Лыжи");

                    b.Navigation("Очки");

                    b.Navigation("Палки");

                    b.Navigation("Сноуборд");

                    b.Navigation("Шлем");
                });

            modelBuilder.Entity("Prokat.API.Models.RentalBooking", b =>
                {
                    b.HasOne("Prokat.API.Models.Order", "Order")
                        .WithMany("Rentals")
                        .HasForeignKey("ID_Заказа")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Prokat.API.Models.Inventory", "Inventory")
                        .WithMany("Rentals")
                        .HasForeignKey("ID_Инвентаря")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Prokat.API.Models.Inventory", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Prokat.API.Models.Order", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
